src/main/java/io/quarkus/search/app/QuarkusVersions.java, src/main/java/io/quarkus/search/app/SearchService.java, src/main/java/io/quarkus/search/app/entity/Guide.java, src/main/java/io/quarkus/search/app/fetching/QuarkusIO.java, src/main/java/io/quarkus/search/app/util/UncheckedIOFunction.java, src/test/data/quarkusio/_versions/2.7/guides/hibernate-orm-panache-kotlin.adoc, src/test/data/quarkusio/_versions/2.7/guides/hibernate-orm-panache.adoc, src/test/data/quarkusio/_versions/2.7/guides/hibernate-orm.adoc, src/test/data/quarkusio/_versions/2.7/guides/hibernate-reactive-panache.adoc, src/test/data/quarkusio/_versions/2.7/guides/hibernate-reactive.adoc, src/test/data/quarkusio/_versions/2.7/guides/hibernate-search-orm-elasticsearch.adoc, src/test/data/quarkusio/_versions/main/guides/hibernate-orm-panache-kotlin.adoc, src/test/data/quarkusio/_versions/main/guides/hibernate-orm-panache.adoc, src/test/data/quarkusio/_versions/main/guides/hibernate-orm.adoc, src/test/data/quarkusio/_versions/main/guides/hibernate-reactive-panache.adoc, src/test/data/quarkusio/_versions/main/guides/hibernate-reactive.adoc, src/test/data/quarkusio/_versions/main/guides/hibernate-search-orm-elasticsearch.adoc, src/test/java/io/quarkus/search/app/SearchServiceTest.java, src/test/java/io/quarkus/search/app/fetching/FetchingServiceTest.java
All of which are needed for integration within quarkus.io
=> Multi-version support, pagination, "categories" filter

src/main/java/io/quarkus/search/app/SearchService.java
To make it extra unlikely that the guide one's looking for is not in the first page.
Compromise to address https://github.com/quarkusio/search.quarkus.io/issues/40#issuecomment-1804124222
cc @gsmet
=> Set the page size to 50

src/main/java/io/quarkus/search/app/hibernate/InputProviderHtmlBodyTextBridge.java, src/main/java/io/quarkus/search/app/util/GitInputProvider.java, src/test/java/io/quarkus/search/app/SearchServiceTest.java
fixes https://github.com/quarkusio/search.quarkus.io/issues/48
This changed the search relevance a bit 😃
=> Extract only actual guide content for fullContent field

README.adoc, src/main/kubernetes/openshift.yml, src/main/resources/application.properties
~Draft as I'm still playing around. OpenSearch really doesn't make it easy to run on OpenShift.~ => Seems to be working now
=> Migrate to OpenSearch

.github/workflows/deploy.yml
=> Second deployment to prod

.github/workflows/build.yml, pom.xml, src/test/java/io/quarkus/search/app/SearchServiceIT.java
=> Remove native tests

pom.xml, src/main/java/io/quarkus/search/app/indexing/IndexingConfig.java, src/main/java/io/quarkus/search/app/indexing/IndexingService.java, src/main/resources/application.properties, src/test/java/io/quarkus/search/app/indexing/SchedulerTest.java
fixes https://github.com/quarkusio/search.quarkus.io/issues/80
=> Add a scheduler for reindexing

src/main/resources/application.properties, src/test/java/io/quarkus/search/app/SearchServiceTest.java
And test that, because that's starting to be a lot of problems.
=> Fix CORS origin regexps

src/main/resources/application.properties
Another attempt at fixing staging.
=> Make sure there are always enough backend connections available

src/main/java/io/quarkus/search/app/util/SimpleExecutor.java
=> Fix exception handling in SimpleExecutor

.github/workflows/build.yml, src/main/java/io/quarkus/search/app/SearchService.java
=> Add import sorting validation to a validation step

src/main/resources/application.properties
The DB connection pool size was too small, it failed in staging :x
=> Adjust indexing parallelism (DB connection pool size, indexing queue count)

src/main/java/io/quarkus/search/app/indexing/IndexingService.java
Apparently even with the latest changes it's still possible for transactions to time out waiting for indexing to finish.
So, let's rely on the global indexing timeout and effectively disable the per-transaction timeout.
=> Avoid transaction timeouts while indexing

src/main/java/io/quarkus/search/app/indexing/FailureCollector.java, src/main/java/io/quarkus/search/app/indexing/IndexingService.java, src/main/java/io/quarkus/search/app/quarkusio/QuarkusIO.java, src/main/java/io/quarkus/search/app/util/UrlInputProvider.java
and here's an example of the message it should produce: https://github.com/marko-bekhta/search.quarkus.io/issues/3#issuecomment-1889796734
=> Add exception stacktrace to the reported status

src/main/java/io/quarkus/search/app/indexing/IndexingService.java, src/main/java/io/quarkus/search/app/util/MutinyUtils.java
Fixes #144
... hopefully. It's a bit of a shot in the dark, since I don't really understand how the problem happened in the first place.
Thanks @marko-bekhta for the suggestion.
Best reviewed commit by commit as I fixed a few other, unrelated and minor things.
=> Wait for cluster to be ready (green) before indexing on startup

src/main/kubernetes/openshift.yml
Attempt at improving performance of our OpenSearch cluster on OpenShift, see #146
=> Raise memory/CPU assigned to OpenSearch on OpenShift

src/main/java/io/quarkus/search/app/hibernate/URIType.java, src/main/java/io/quarkus/search/app/quarkusio/QuarkusIO.java, src/main/java/io/quarkus/search/app/util/ExceptionUtils.java, src/test/java/io/quarkus/search/app/testsupport/GitTestUtils.java
Hi all; figured log a first one to see if there's appetite for more automated code changes to adopt new code patterns.
Use this link to re-run the recipe: https://app.moderne.io/recipes/org.openrewrite.staticanalysis.InstanceOfPatternMatch?organizationId=UXVhcmt1cw%3D%3D
=> refactor: Changes code to use Java 17's `instanceof` pattern matching

README.adoc, src/main/kubernetes/openshift.yml
See https://github.com/quarkusio/quarkus/issues/38455
=> Move to Deployment instead of DeploymentConfig

src/main/java/io/quarkus/search/app/util/GitCloneDirectory.java
https://github.com/quarkusio/search.quarkus.io/issues/131#issuecomment-1921604152
Tested this locally from a cleanly cloned repo with depth=1 and it worked. And it seems like a good place as each localized site may have its state of the submodule...
=> Fetch missing upstream submodule ref if needed

src/main/java/io/quarkus/search/app/indexing/FailureCollector.java
hey 😃 
soooo looking at those loooooooooooooooooong comments from earlier today, I thought we can hide more text, so it's easier to scroll that reporting issue, here are a couple of examples:
message too long (turns out that there's a comment length limit, and if it is too long the API will reject the request and we wouldn't report anything without even knowing 🙈) : https://github.com/marko-bekhta/search.quarkus.io/issues/3#issuecomment-1924032731
ok message: https://github.com/marko-bekhta/search.quarkus.io/issues/3#issuecomment-1924033992
=> Update formatting of a comment in a github failure reporter

src/main/java/io/quarkus/search/app/util/GitCloneDirectory.java
I couldn't find a way to somehow pass on which rev to run the submodule command, and also didn't see some file from which we could read the hash, sooo that's what I ended up with 🙈
=> Change how git submodule status is retrieved

src/main/java/io/quarkus/search/app/util/GitCloneDirectory.java
https://github.com/quarkusio/search.quarkus.io/issues/199
I 🤔 I've tracked down the issue to this fetch-update block ... See the comment for what I'm seeing when executing this locally...
=> Change fetch call options

src/main/resources/web/app/qs-form.ts, src/main/resources/web/app/qs-guide.ts, src/main/resources/web/app/qs-target.ts
- Fixes an issue when stopping a search before it displayed the results (loading indicator was staying)
- Should fix CORS issue (preflight request)
=> Flow fixes in search web component

src/main/java/io/quarkus/search/app/dto/GuideSearchHit.java, src/test/java/io/quarkus/search/app/SearchServiceTest.java, src/test/java/io/quarkus/search/app/SynonymSearchServiceTest.java
See https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/search.2Equarkus.2Eio/near/431900183
=> Add ellipses to the highlighted snippets

src/main/resources/web/app/qs-form.ts
=> Fix loading and error handling

src/main/resources/web/app/qs-form.ts
I will test it tomorrow, I coded it in the GH editor (unless someone can test it)
=> Fix search when category is empty

src/main/resources/web/app/local-search.ts, src/main/resources/web/app/qs-form.ts, src/main/resources/web/app/qs-guide.ts, src/main/resources/web/app/qs-target.ts
fixes https://github.com/quarkusio/search.quarkus.io/issues/252, https://github.com/quarkusio/search.quarkus.io/issues/251
=> Search form updates

src/main/resources/web/app/qs-form.ts, src/main/resources/web/app/qs-target.ts
Fixes quarkusio/quarkusio.github.io#1917
=> Add query parameters to the url

src/main/resources/application.properties, src/main/resources/web/app/qs-guide.ts, src/main/resources/web/app/style.scss
fixes https://github.com/quarkusio/quarkusio.github.io/issues/2007 
+fixes https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/Quarkus.2Eio.20search/near/444013207
The icons disappeared as the bundler property key got updated 😕
=> Fix some dark mode issues / add back the guide icons

src/main/resources/application.properties
I think this should do it 😞 😢 😭
=> Fix env variable for ES hosts

src/main/java/io/quarkus/search/app/util/GitCloneDirectory.java
fixes https://github.com/quarkusio/search.quarkus.io/issues/293
Use the local ref database instead of calling ls-remote. This worked ok locally 🙈 let's see if CI and staging will also agree
=> Change how git ref id is obtained

src/main/java/io/quarkus/search/app/entity/Guide.java, src/main/java/io/quarkus/search/app/hibernate/GuideLoadingBinder.java, src/main/java/io/quarkus/search/app/hibernate/QuarkusIOLoadingContext.java
that came up after the blog post review 😉
=> Some minor cleanups around the loading binder

src/main/resources/web/app/qs-guide.ts
and don't make the url relative if it is not an absolute url to start with...
=> Fix local search guide rendering

src/main/kubernetes/openshift.yml
- which actually causes issues
=> Remove a redundant double quote in the env variable

src/main/java/io/quarkus/search/app/indexing/IndexingService.java
Yeah, so it's kind of embarrassing. Let's merge and not talk about it?
See also https://quarkusio.zulipchat.com/#narrow/channel/187038-dev/topic/Something.20is.20wrong.20with.20docs.20search
=> Do not ignore mass indexing failures

src/main/helm/values.staging.yaml
It's getting tight... let's hope we still manage to index in ~15 minutes.
See https://github.com/quarkusio/search.quarkus.io/issues/131#issuecomment-2568856874
=> Reduce resource usage even more on staging

README.adoc
I already updated the description of prod/staging issues accordingly:
https://github.com/quarkusio/search.quarkus.io/issues/130
https://github.com/quarkusio/search.quarkus.io/issues/131
=> Mention Search Web UI in README.adoc

src/main/resources/web/app/qs-form.ts
fixes https://github.com/quarkiverse/quarkiverse-docs/issues/207
=> Do not reset link hash if no query data read from the url
