quarkusio/search.quarkus.io

- src/main/java/io/quarkus/search/app/indexing/IndexingConfig.java
- src/main/java/io/quarkus/search/app/indexing/IndexingService.java
- src/main/kubernetes/openshift.yml
- src/main/resources/application.properties
Taking advantage of https://quarkus.io/guides/deploying-to-kubernetes#using-existing-resources
> Include Elasticsearch service in the OpenShift deployment

- pom.xml
I looked, @gsmet , and there doesn't seem to be a solution to your problem at the moment. Test names in console reports will be crappy, that's how it is until someone contributes a patch to surefire.
We can only improve the XML reports, and only through these explicit settings.
> Better test names in test reports

- src/main/kubernetes/openshift.yml
- src/main/resources/application.properties
This is how you maintain a fixed number of individually addressable nodes, apparently.
> Redefine elasticsearch deployment as a StatefulSet

- pom.xml
- src/main/java/io/quarkus/search/app/health/IndexContentHealthCheck.java
- src/main/java/io/quarkus/search/app/indexing/IndexingService.java
- src/main/java/io/quarkus/search/app/indexing/Rollover.java
- src/main/resources/application.properties
- src/test/java/io/quarkus/search/app/SearchServiceTest.java
The main reason for this change is to improve startup on openshift, which doesn't work well if we do a very long blocking operation in a CDI listener. So, asynchronous is better.
Zero-downtime indexing... turned out to not be necessary in the end, but will be useful eventually anyway (when we want to reindex upon Quarkus releases), so let's keep it :)
> Zero-downtime indexing + asynchronous indexing on startup

- src/main/java/io/quarkus/search/app/indexing/IndexingService.java
- src/main/java/io/quarkus/search/app/indexing/Rollover.java
Follows up on #23
Apparently Hibernate Search can't drop indexes when write and read aliases are inconsistent, so we have to do it manually.
This time I reproduced the issue locally and checked that recovery works.
> Better recovering for inconsistent aliases

- src/main/java/io/quarkus/search/app/indexing/Rollover.java
- src/test/java/io/quarkus/search/app/indexing/RolloverTest.java
... and add automated tests for it.
> Make sure search functionality is restored immediately upon rollover recovery

- src/main/java/io/quarkus/search/app/fetching/QuarkusIO.java
- src/test/java/io/quarkus/search/app/SearchServiceTest.java
- src/test/java/io/quarkus/search/app/fetching/FetchingServiceTest.java
For some reason quarkus.io in its source code uses `/_versions/`, but the generated site uses `/version/`...
> Use the correct `/version/` instead of `/versions/` in guide HTTP paths

- src/main/resources/application.properties
Makes it work for subdomains and surge.sh previews.
Also, it seems CORS only matches the protocol + host, so I don't think we need to account for URL paths.
> More flexible CORS settings

- src/main/java/io/quarkus/search/app/SearchService.java
- src/test/java/io/quarkus/search/app/SearchServiceTest.java
See https://github.com/quarkusio/quarkusio.github.io/pull/1825#issuecomment-1805779948
I suspect we'll come to regret this when we'll introduce more complex queries, e.g. to query both english and japanese fields, which have different analyzers and thus can't be targeted in the same predicate.
But I guess that's a problem for another day.
> Use the AND operator by default for multi-term queries

- src/main/java/io/quarkus/search/app/SearchService.java
- src/main/java/io/quarkus/search/app/dto/GuideSearchHit.java
- src/main/java/io/quarkus/search/app/dto/SearchHit.java
- src/main/java/io/quarkus/search/app/entity/Guide.java
- src/main/java/io/quarkus/search/app/fetching/QuarkusIO.java
- src/main/java/io/quarkus/search/app/indexing/IndexingService.java
- src/main/java/io/quarkus/search/app/yml/QuarkusMetadata.java
- src/main/resources/application.properties
- src/main/resources/indexes/mapping-template.json
- src/main/resources/indexes/settings-template.json
- src/test/java/io/quarkus/search/app/SearchServiceTest.java
- src/test/java/io/quarkus/search/app/fetching/FetchingServiceTest.java
- src/test/java/io/quarkus/search/app/testsupport/GuideRef.java
fixes https://github.com/quarkusio/search.quarkus.io/issues/39
I've used the unified highlighter as that is the one that Elasticsearch is maintaining on their own and have their own custom version. 
I had to remove `fullContent` field from excluded as otherwise we wouldn't be able to do highlighting on that field. Aaaand that lead to the problem as the content is really long and the search query will fail. I've increased the `max_analyzed_offset` from `1000000` to `5000000`. Alternatively, we could've use the `max_analyzed_offset` (https://www.elastic.co/guide/en/elasticsearch/reference/current/highlighting.html#max-analyzed-offset) but we didn't add it as an exposed option 🙈 and I didn't want to get into customizing the JSON 😃.
A couple of search results:
looking for a config property …
> Enable highlighting on title/summary/fullContent

- pom.xml
- src/main/java/io/quarkus/search/app/SearchService.java
- src/main/java/io/quarkus/search/app/entity/Guide.java
- src/main/java/io/quarkus/search/app/hibernate/AnalysisConfigurer.java
- src/main/java/io/quarkus/search/app/hibernate/InputProviderHtmlBodyTextBridge.java
- src/main/java/io/quarkus/search/app/quarkusio/QuarkusIO.java
- src/main/java/io/quarkus/search/app/util/MarkdownRenderer.java
- src/test/java/io/quarkus/search/app/util/ParserTest.java
fixes https://github.com/quarkusio/search.quarkus.io/issues/60
Not sure which library you had in mind to render the summaries, so I tried `commonmark`.  Simple rendering of HTML doesn't produce great results, since we have the HTML encoder applied for highlights. that means that the returned text cannot be easily inserted into the page. Also, since the highlighter is applied to the "source" we will still get the link path highlighted, making things worse 😄.
A couple of options that we have:
* using an HTML renderer, will produce (just to show what we are ending up with...):
```html
&lt;p&gt;Quarkus DI solution is based on the &lt;a href=&quot;https:&#x2F;&#x2F;jakarta.ee&#x2F;specifications&#x2F;<span class=\"highlighted\">cdi</span>&#x2F;4.0&#x2F;jakarta-<span …
```
> Convert the summary that may be written in markdown before indexing

- pom.xml
- src/main/java/io/quarkus/search/app/SearchService.java
- src/main/java/io/quarkus/search/app/entity/Guide.java
- src/main/java/io/quarkus/search/app/fetching/FetchingService.java
- src/main/java/io/quarkus/search/app/health/IndexContentHealthCheck.java
- src/main/java/io/quarkus/search/app/health/IndexSchemaHealthCheck.java
- src/main/java/io/quarkus/search/app/hibernate/AnalysisConfigurer.java
- src/main/java/io/quarkus/search/app/hibernate/InputProviderHtmlBodyTextBridge.java
- src/main/java/io/quarkus/search/app/hibernate/URIType.java
- src/main/java/io/quarkus/search/app/indexing/IndexingService.java
- src/main/java/io/quarkus/search/app/indexing/Rollover.java
- src/main/java/io/quarkus/search/app/quarkusio/QuarkusIO.java
- src/main/java/io/quarkus/search/app/util/GitInputProvider.java
- src/main/java/io/quarkus/search/app/util/UncheckedIOFunction.java
- src/main/java/io/quarkus/search/app/util/UrlInputProvider.java
- src/test/java/io/quarkus/search/app/SearchServiceTest.java
- src/test/java/io/quarkus/search/app/SynonymSearchServiceTest.java
- src/test/java/io/quarkus/search/app/fetching/FetchingServiceTest.java
- src/test/java/io/quarkus/search/app/indexing/RolloverTest.java
- src/test/java/io/quarkus/search/app/testsupport/GitCopier.java
- src/test/java/io/quarkus/search/app/testsupport/GitTestUtils.java
- src/test/java/io/quarkus/search/app/testsupport/QuarkusIOSample.java
I keep missing an import here and there, so I thought that maybe we should add the imports plugin to the build as well since we already have the code-formatter one...
> Add plugin to sort/remove unused imports

- src/main/resources/application.properties
https://quarkus-website-pr-1825-preview.surge.sh/guides/ has become https://quarkus-site-pr-1825-preview.surge.sh/guides/, no idea why.
> Update CORS rules to allow new URL of quarkus.io previews

- src/main/resources/application.properties
Currently, deployment is failing on staging because indexing takes longer than allowed by the startup probe.
See also #90
> Allow for (very) slow app startup due to cloning many large git repositories

- src/main/java/io/quarkus/search/app/fetching/FetchingConfig.java
- src/main/java/io/quarkus/search/app/fetching/FetchingService.java
- src/main/java/io/quarkus/search/app/fetching/LoggerProgressMonitor.java
- src/main/java/io/quarkus/search/app/indexing/IndexingConfig.java
- src/main/java/io/quarkus/search/app/indexing/IndexingService.java
- src/main/java/io/quarkus/search/app/util/ExceptionUtils.java
- src/main/java/io/quarkus/search/app/util/GitCloneDirectory.java
- src/main/java/io/quarkus/search/app/util/SimpleExecutor.java
- src/main/resources/application.properties
- src/test/java/io/quarkus/search/app/fetching/FetchingServiceTest.java
Fixes #90 (and a bit more, since indexing now happens in parallel as well).
Better reviewed commit by commit, since the first commit in particular is quite disruptive.
> Parallelize guide fetching and indexing

- src/main/kubernetes/openshift.yml
The default, 600, doesn't seem to be enough.
We reindex all data on deployment, and that takes time.
> Lower the Rolling strategy timeout

- src/main/resources/application.properties
Fixes #100 (I think)
We only use the DB when indexing, so it's very likely the DB will not be used for hours, and we don't want H2 to close it automatically, because then we'll lose all schemas.
> Avoid closing (and losing) the DB after some inactivity

- src/main/java/io/quarkus/search/app/SearchService.java
- src/main/java/io/quarkus/search/app/entity/Guide.java
- src/main/java/io/quarkus/search/app/entity/VersionAndLanguageRoutingBinder.java
- src/main/resources/indexes/settings-template.json
Not sure we should merge this, as performance didn't improve (see https://docs.google.com/spreadsheets/d/1w0tSfL-MKFArSrB-L8IX1pxmrhWmQyNgNwQRloG3cLk/edit#gid=456110917)
Maybe we should just keep the routing part (because it simplifies queries a bit) and drop the sharding config?
> Enable routing by version + language

- pom.xml
- src/main/java/io/quarkus/search/app/SearchService.java
- src/test/java/io/quarkus/search/app/SearchServiceTest.java
In particular for highlighting, which could perform badly with high numbers of snippets or high snippet length.
> Add validation to search endpoint query parameters

- src/main/java/io/quarkus/search/app/SearchService.java
- src/test/java/io/quarkus/search/app/SearchServiceTest.java
it seems like it worked fine 😃 
Note that the highlighted text still has each word wrapped on its own. We can try switching to a fast vector highlighter, which should be able to better wrap a few words in the same tags, but unless we reallyyyyyy need that I'd stay on a unified one 😃
> Accept quotes for phrase matching in a query

- src/main/java/io/quarkus/search/app/quarkusio/QuarkusIO.java
- src/main/java/io/quarkus/search/app/util/GitInputProvider.java
- src/main/java/io/quarkus/search/app/util/GitUtils.java
It can happen, and so it did 😃, that some guide HTML file is not here in a localized repository. Currently, this would result in an exception, and the entire indexing thing will fail. But since the HTML is not there, it means the user won't be able to open it anyway, so there is no point in displaying such a record in the guide search results. And we can just ignore persisting such guide entity.
> Skip translated Quarkus guides that do not have an HTML in a git repository

- src/main/kubernetes/openshift.yml
The last change to that size was supposed to set it to 512MiB but mistakenly set it to 512GiB... which is way too much.
Currently we only use ~500MB per index, and this will rise to ~1GB per index after #117, so 5GiB should be more than enough and leave room for changes to analysis config and indexing of more content in the foreseable future.
> Set volume claim size to 5GiB

- pom.xml
- src/test/java/io/quarkus/search/app/testsupport/QuarkusIOSample.java
So that it is easier to see if we use deprecated APIs. I noticed that we didn't have this in place while I was updating the tests in Search with the most recent Assertj update.
> Add a compiler deprecation check

- src/main/resources/application.properties
Because OpenSearch can only handle so many pending indexing requests, and it's been failing to handle some of them in the staging/prod environments.
> Limit parallelism of indexing

- src/main/java/io/quarkus/search/app/util/SimpleExecutor.java
When we have many more producers of documents than consumers, some producers might end up waiting for a long time. We want producers to be consumed in FIFO order.
> Reduce the risk of transaction timeouts

- src/main/java/io/quarkus/search/app/fetching/FetchingService.java
- src/main/java/io/quarkus/search/app/quarkusio/QuarkusIO.java
- src/main/java/io/quarkus/search/app/util/CloseableDirectory.java
- src/main/java/io/quarkus/search/app/util/GitCloneDirectory.java
- src/test/java/io/quarkus/search/app/fetching/FetchingServiceTest.java
- src/test/java/io/quarkus/search/app/testsupport/QuarkusIOSample.java
fixes https://github.com/quarkusio/search.quarkus.io/issues/85
fixes #126
Now `QuarkusIo` will only close the quarkiverse guides directory; repositories are going to be closed on the fetching bean been destroyed.
If we are pointing to a local dir repository then the fetching part is quick as there's nothing to pull/fetch and only zip files do not have an actual remote that can be called, so that one has a "special treatment" 😃
> Keep git clones on disk and update them instead of re-cloning on each reindexing

- src/main/resources/application.properties
To minimize impact of https://github.com/quarkusio/search.quarkus.io/issues/138 on users.
> Index at 00:00 instead of 19:00

- README.adoc
- src/main/java/io/quarkus/search/app/SearchService.java
- src/main/java/io/quarkus/search/app/dto/SearchResult.java
- src/main/java/io/quarkus/search/app/entity/Guide.java
- src/main/kubernetes/openshift.yml
- src/test/java/io/quarkus/search/app/SearchServiceTest.java
- src/test/java/io/quarkus/search/app/indexing/SchedulerTest.java
Fixes #149
Most of the commits about perf improvement are pointless, but make sense regardless, so I kept them:
* pod affinity doesn't change anything since our cluster has only one zone, but it's good practice
* the total hit count threshold doesn't change much to performance, but since clients don't use the total anyway, we might as well not waste time on computing it
The actual improvement lies in "Store term vectors on Guide#fullContent for faster highlighting".
Yes, this doubles the size of indexes (to something like 700MB).
But. This also halves the execution time of queries. In dev mode I got from a 99th percentile of 440ms to 220ms.
I don't think the effect will be quite as dramatic in prod, but it's at least worth a shot, I think.
> Further work on performance improvements

- src/main/resources/application.properties
- src/test/java/io/quarkus/search/app/SearchServiceTest.java
So that things like https://quarkus-pr-main-38430-preview.surge.sh don't fail to run search anymore.
> Allow Quarkus Core repo PR previews in CORS

- src/main/kubernetes/openshift.yml
It's not available on Deployment, only on DeploymentConfig. Let's hope the default timeout works fine.
> Remove rolling update timeout

- src/main/java/io/quarkus/search/app/fetching/FetchingService.java
- src/main/java/io/quarkus/search/app/indexing/FailureCollector.java
- src/main/java/io/quarkus/search/app/quarkusio/QuarkusIO.java
- src/main/java/io/quarkus/search/app/util/GitCloneDirectory.java
- src/main/java/io/quarkus/search/app/util/GitInputProvider.java
- src/main/java/io/quarkus/search/app/util/GitUtils.java
- src/test/java/io/quarkus/search/app/testsupport/QuarkusIOSample.java
Opening as a draft so we have a place to discuss this 😃 
so the idea here is that we can check if the upstream in localized site is the same thing that main was generated from, and if it is -- we'd be expecting that all files should be in place (either translated, or original ones) and if some are missing then that's a problem. 
now as there was a problem once that es site didn't get synced for some time I thought it may be ok to log a warning in that case... that's that part about the `localizedSitesUpToDate` map.  if that makes sense, we could also extract the acceptable period to a configurable property.
> Fewer warnings on translations (Use rev trees for reading sources and HTMLs)

- src/main/java/io/quarkus/search/app/hibernate/AnalysisConfigurer.java
Well.... maybe not wonderful 🤣  but it seems a bit better. My thinking here is that since we 100% want to have the analyzer/autocomplete analyzer to use the same filters in the same order with autocomplete one adding the ngrams, there's no need to repeat the lists...  
Then IDK about you, but reading the filters one in the line seems easier 😃.  I've also added a few more comments, not necessarily all for us 🙈 😃
> (hopefully) Better grouping of analyzer configs

- src/main/java/io/quarkus/search/app/fetching/FetchingService.java
- src/main/java/io/quarkus/search/app/indexing/IndexingService.java
- src/main/java/io/quarkus/search/app/quarkusio/QuarkusIO.java
- src/main/java/io/quarkus/search/app/util/MutinyUtils.java
- src/main/resources/application.properties
- src/test/java/io/quarkus/search/app/indexing/RolloverTest.java
- src/test/java/io/quarkus/search/app/indexing/SchedulerTest.java
- src/test/java/io/quarkus/search/app/testsupport/GitTestUtils.java
A few fixes that make the build pass even when we [reuse the OpenSearch container](https://quarkus.io/guides/elasticsearch-dev-services#reuse) between tests.
> Allow container reuse

- .github/workflows/deploy.yml
- Dockerfile
- README.adoc
- pom.xml
- src/main/docker/opensearch-custom.Dockerfile
- src/main/helm/values.prod.yaml
- src/main/helm/values.staging.yaml
- src/main/kubernetes/openshift.yml
- src/main/resources/application.properties
Because the cluster is kind of overloaded right now, so we'll have no chance to deploy if we ask for too much cpu/memory.
Creating as draft; let's merge on Tuesday, when I'll have time to deal with deployment errors. I tested manually and it worked, but who knows.
> Use quarkus-helm for deployment, set lower resource requirements on staging 

- src/test/java/io/quarkus/search/app/SearchServiceTest.java
- src/test/java/io/quarkus/search/app/SynonymSearchServiceTest.java
- src/test/java/io/quarkus/search/app/indexing/SchedulerTest.java
- src/test/java/io/quarkus/search/app/testsupport/SetupUtil.java
Otherwise we pollute logs with many healthcheck failures.
> Less aggressive polling when waiting for indexing in tests

- src/main/resources/web/app/qs-form.ts
- src/main/resources/web/app/qs-target.ts
There was a bug where when searching multiple times, it was not correctly updating the results (because of some internal lit caching issue).
Making sure it shows the load indicator is enforcing the items to be refreshed.
> Fix bug wc loading

- src/main/java/io/quarkus/search/app/quarkusio/QuarkusIO.java
- src/main/java/io/quarkus/search/app/util/GitCloneDirectory.java
- src/main/java/io/quarkus/search/app/util/GitUtils.java
See https://github.com/quarkusio/search.quarkus.io/issues/130#issuecomment-2040995960
So it was supposed to be a warning, it's just that the runtime exception from `gitutils#file` was never caught all the way up to the indexing...
> Adjust how translation missing exception is handled

- src/main/java/io/quarkus/search/app/ReferenceService.java
- src/main/java/io/quarkus/search/app/entity/Language.java
Fixes an invalid schema generated by Smallrye-OpenAPI, where enums were represented by their name instead of their code:
Becomes:
> Properly define serialization of Language (for OpenAPI in particular)

- src/main/resources/web/app/qs-form.ts
Without this, other form elements can trigger undesired search as mentioned here https://github.com/quarkusio/quarkusio.github.io/pull/1895#issuecomment-2042758187
> Use only form elements with the name attribute defined

- src/main/resources/web/app/qs-target.ts
fixes #230
And here's a screen of how the loading looks with increased padding:
> Update search component

- src/main/resources/web/app/qs-form.ts
Attributes passed to the form, such as `quarkus-version` are not yet initialized in the constructor and if we read the form data in the constructor all of those attr values will not be in the initial search request (can happen when a link with a search query is shared/opened)
> Read query input parameters when the form is fully initialized

- src/main/java/io/quarkus/search/app/indexing/FailureCollector.java
- src/test/java/io/quarkus/search/app/indexing/FailureCollectorTest.java
First for convenience: you can see what's happened with just a look at the email subject or issue title.
Second, to solve a problem with the current way we add comments: we never add a comment for successes, and we don't duplicate warning comments... so when reindexing occurs after a warning, we don't know whether the new indexing has succeeded or still has the same warnings!
> Insert status in GitHub issue indexing reports

- src/main/resources/web/app/qs-guide.ts
- src/main/resources/web/app/qs-target.ts
fixes https://github.com/quarkusio/search.quarkus.io/issues/273
That's what I was thinking of ... 
By the way, the `_target` was always blank since we were returning all the URLs as absolute. With the change, Quarkus guides will open on the same page as the search, while Quarkiverse guides will open in a new tab. Do we want to keep opening Quakrus guides in the new tab?
> Use relative URLs for quarkus guides

- pom.xml
- src/main/docker/opensearch-custom.Dockerfile
- src/main/resources/application.properties
The build for Hibernate Search passed https://github.com/hibernate/hibernate-search/pull/4211
So we can try it here as well 😃. (before dependabot opens a PR for it 😈😆)
> Update to OpenSearch 2.15

- src/main/helm/values.staging.yaml
So that OpenSearch don't end up leaving requests hanging for more than 30s.
Fixes #290, hopefully.
> Send fewer indexing requests to OpenSearch in parallel on staging

- src/main/java/io/quarkus/search/app/indexing/reporting/GithubStatusReporter.java
- src/main/java/io/quarkus/search/app/indexing/reporting/LogStatusReporter.java
- src/main/java/io/quarkus/search/app/indexing/reporting/Status.java
- src/main/java/io/quarkus/search/app/indexing/reporting/StatusRenderer.java
- src/main/java/io/quarkus/search/app/indexing/state/IndexingState.java
- src/test/java/io/quarkus/search/app/indexing/reporting/StatusRendererTest.java
- src/test/java/io/quarkus/search/app/indexing/state/IndexingStateTest.java
So that we see something like this when we look at the GitHub issue:
> Update GitHub issue title when indexing starts

- src/main/helm/values.staging.yaml
- src/main/java/io/quarkus/search/app/SearchService.java
- src/main/java/io/quarkus/search/app/entity/Guide.java
- src/main/java/io/quarkus/search/app/hibernate/AnalysisConfigurer.java
- src/main/java/io/quarkus/search/app/indexing/IndexingService.java
- src/main/resources/application.properties
- src/test/java/io/quarkus/search/app/SearchServiceTest.java
- src/test/java/io/quarkus/search/app/SynonymSearchServiceTest.java
I couldn't reproduce the same amount of slowness local as in prod, but I suspect hardware might be to blame... Heap size for OpenSearch -- as well as the app --  is the same as in prod.
In any case, search was still relatively slow on my machine at ~100ms per query. Disabling highlighting brought me to 10ms, proving that, as expected, highlighting is to blame.
So I switched to the fast-vector highlighter and saw a small improvement: instead of ~100ms, queries now take ~50 to ~70ms (still on my laptop). I had to remove stop-words filters and change the boundary scanner, but otherwise highlighted snippets seem similar.
Hopefully the improvement will be similar in prod.
I also added a force-merge after indexing because... why not. I experimented with concurrent fragment search, but this …
> Use fast-vector highlighting and force-merge after indexing

- pom.xml
- src/main/docker/opensearch-custom.Dockerfile
- src/main/resources/application.properties
Tests in Hibernate Search passed. 
Looking at the release notes: https://github.com/opensearch-project/OpenSearch/releases/tag/2.18.0 I didn't see anything of particular interest (except that now there's a phone analyzer soooo if we need to search for phone numbers ... 😃)
> Update to OpenSearch 2.18

- src/main/helm/values.staging.yaml
So that hopefully we'll find an available node in the cluster to host us.
See https://github.com/quarkusio/search.quarkus.io/issues/131#issuecomment-2461660954
> Reduce resource usage on staging

- src/main/resources/application.properties
It seems documents have gotten bigger and are now saturating the OpenSearch memory, which is rather restricted in our current setup, leading to failures.
> Reduce side of bulks when indexing in dev, tests and prod

- src/main/java/io/quarkus/search/app/indexing/reporting/FailureCollector.java
- src/main/java/io/quarkus/search/app/indexing/reporting/GithubStatusReporter.java
- src/main/java/io/quarkus/search/app/indexing/state/IndexingState.java
- src/main/java/io/quarkus/search/app/quarkusio/QuarkusIO.java
- src/main/java/io/quarkus/search/app/util/GitUtils.java
- src/test/java/io/quarkus/search/app/indexing/state/IndexingStateTest.java
And don't report them on GitHub if there is nothing more serious,
to create less noise with GitHub notifications.
> Report some failures at INFO level only

- .github/workflows/deploy.yml
- README.adoc
- pom.xml
- src/main/docker/elasticsearch-custom.Dockerfile
- src/main/helm/values.staging.yaml
- src/main/kubernetes/openshift.yml
- src/main/resources/application.properties
Fixes #358
``` bash
mvn clean install -Pes
```
To run with Elasticsearch. But that's just for tests; there's other things in the deployment side that reference OpenSearch that I haven't looked at 🙈
> Run tests with Elasticsearch

- src/main/kubernetes/openshift.yml
i.e. add missing `enabled` to the cluster.deprecation_indexing.enabled
> Use correct property name for deprecation indexing

- src/main/resources/application.properties
This reverts commit c24d1804c6edf05e518ab27b8c6740df362ccf05.
It didn't solve anything, and probably wasn't relevant since the failure seems to happen when searching (?!)
> Revert "Reduce side of bulks when indexing in dev, tests and prod"

- src/main/helm/values.staging.yaml
As discussed, the previous config seems to lead to indexing failures in the staging environment due to Elasticsearch tripping memory-related circuit breakers and/or timing out.
> Reduce pressure on Elasticsearch in staging env

- src/main/java/io/quarkus/search/app/hibernate/InputProviderHtmlBodyTextBridge.java
Not sure if that's worth it or not (it'll log up to 10k chars)...  but I noticed this again when looking at the recent staging logs: https://github.com/quarkusio/search.quarkus.io/issues/319#issuecomment-2507958384 
But looking at the files it points to, those seem fine and running the app locally does not produce the warning ... so I wonder what's the content of those files if it says they aren't what we expect ...
> Include part of the guide body that has unexpected formatting in the logged message

- src/main/helm/values.staging.yaml
This reverts commit 40deeae3b69e6eefea2036ea9aef2858654e51b5.
Resources are _too_ constrainted now, and we're tripping timeouts. I guess we could raise timeouts, but since it's been confirmed we were not using too much resources, let's make this run faster.
> Revert "Reduce resource usage even more on staging"

- src/main/resources/application.properties
as now, it also includes Quarkiverse guides, increasing the overall indexing time. Looking at staging we've got:
```
07:55:27 INFO [i.qu.se.ap.hi.StreamMassIndexingLoggingMonitor] Mass indexing is going to index an entity stream. Total is not known at this point.
....
08:05:22 INFO [i.qu.se.ap.hi.StreamMassIndexingLoggingMonitor] Mass indexing progress: indexed 6150 entities in 513720 ms.
08:05:27 ERROR [o.hi.se.ma.po.ma.im.PojoMassIndexingNotifier] HSEARCH000062: Mass indexing received interrupt signal: aborting.
```
> Increase indexing timeout

- src/main/java/io/quarkus/search/app/SearchService.java
- src/main/java/io/quarkus/search/app/ui/SearchUiConfig.java
- src/main/java/io/quarkus/search/app/ui/SearchUiService.java
- src/main/resources/application.properties
to not rely on launch mode but on profiles instead. This way staging, that also runs in a normal launch mode can benefit from the index search page
> Adjust the condition of not returning index.html

- README.adoc
- src/main/java/io/quarkus/search/app/fetching/FetchingService.java
- src/main/java/io/quarkus/search/app/quarkiverseio/QuarkiverseIO.java
- src/main/java/io/quarkus/search/app/quarkiverseio/QuarkiverseIOConfig.java
- src/main/resources/application.properties
- src/test/java/io/quarkus/search/app/SearchServiceQuarkiverseTest.java
I had some trouble setting this up in my dev env, so I thought this could make sense...
`quarkiverseio.source` can be set to `none`, `zip` or `github-artifact`, which will get the ball rolling provided you set your token (for `github-artifact`) or path (for `zip`).
Also, use the `_DEV_` prefix for the recommended options to download Quarkiverse in dev mode, otherwise the .env file might affect tests.
NOTE: Upon merging, we may need to clean up the staging config. I think removing everything except the token from the config map should do the trick.
> Simplify configuration of Quarkiverse.io fetching

- src/main/java/io/quarkus/search/app/SearchService.java
- src/test/java/io/quarkus/search/app/SearchServiceQuarkiverseTest.java
- src/test/java/io/quarkus/search/app/testsupport/GuideRef.java
So that Quarkiverse guides are generally lower in the result list, but are not sent down to oblivion either.
See examples below (you won't believe the last one! cc @gsmet)
| Before  | After |
| ------------- | ------------- |
| ![image](https://github.com/user-attachments/assets/a6c5c26e-547b-48f6-a00d-38ef97461065) | ![image](https://github.com/user-attachments/assets/32a5182f-98b6-4e50-b73c-97e6f2fd5bc4)  |
| Before  | After |
| ------------- | ------------- |
| ![image](https://github.com/user-attachments/assets/36a76cce-d3d5-49ab-804e-c079f84fde0b)  | ![image](https://github.com/user-attachments/assets/3e24ec13-0e6e-46bf-9c7d-44aafeefd5d6)  |
| Before  | After |
| ------------- | ------------- |
| ![image](https://github.com/user-attachments/assets/646385f5-0322-4b52-843f-61b2a7ae47cc) …
> Improve relative relevance of quarkus.io guides vs quarkiverse.io guides

- src/main/java/io/quarkus/search/app/SearchService.java
- src/main/java/io/quarkus/search/app/dto/SearchResult.java
- src/main/java/io/quarkus/search/app/entity/Guide.java
- src/main/java/io/quarkus/search/app/hibernate/AnalysisConfigurer.java
- src/main/resources/web/app/qs-form.ts
- src/main/resources/web/app/qs-target.ts
- src/test/java/io/quarkus/search/app/SearchServiceTest.java
Fixes #306 
Hey @yrodiere 
I was going through some tickets at HSEARCH 😃 and noticed one submitted by the community about suggesters, but without much info. Hence, I thought I'd take a closer look at the suggesters before closing the ticket 🙈 and it turned out to be an interesting feature. This PR tests how we could leverage from it in search.quarkus.io. 
While at it, I thought: should we give users a way to manipulate the request JSON before we send it (like in this PR we are adding another top-level element to the JSON, so adding things through e.g. a JSON predicate, wouldn't really work...)
Some links:
- https://www.elastic.co/guide/en/elasticsearch/reference/current/search-suggesters.html
- https://lucene.apache.org/core/10_0_0/suggest/index.html
> Experiments: Add possible suggestion to the empty results response

- pom.xml
- src/main/helm/values.staging.yaml
Staging keeps struggling to get up though it got a bit further with the patch 😖. I've also increased the thresholds for health checks to more or less match the times that we've set for the `startup-probe`
> Increase memory limit for staging / Increase health probe thresholds

- src/main/helm/values.staging.yaml
The app seems to be overloading Elasticsearch... again.
> Raise memory allocated to Elasticsearch on staging

- .github/workflows/build.yml
Missed that other PR by a minute 😄 
not sure about the `quarkusio/action-build-reporter`, do we keep its version floating?
> Use SHA instead of versions in GH actions

- pom.xml
- src/main/docker/opensearch-custom.Dockerfile
While testing with it is easy... just:
```
mvn clean install -Popensearch
```
Running the tests leads to all those issues we had with the OpenSearch backend in the first place:
```
HSEARCH400007: Elasticsearch request failed: HSEARCH400090: Elasticsearch response indicates a failure.
"reason": "[parent] Data too large, data for [\u003chttp_request\u003e] would be [1053417574/1004.6mb], which is larger than the limit of [1020054732/972.7mb], real usage: .... 
```
sooooo dropping the profile it is then 🥲
> Remove OpenSearch profile

- pom.xml
- src/main/docker/elasticsearch-custom.Dockerfile
- src/main/resources/application.properties
we'll upgrade to 9.0 once it's "supported" in the Hibernate Search version included in Quarkus
> Update to Elasticsearch 8.18

- pom.xml
- src/main/resources/application.properties
I reverted to some older commit
(cc66a99955fb5f6231c09940c063d81fe4f5116b)
and ran `quarkus update`.
It found a deprecated config (CORS-related), and also an unnecessary version in dependencies (it's managed further up in the same POM).
> Run `quarkus update`

- .github/workflows/build.yml
> Improve build reporting

- .github/workflows/build.yml
- .github/workflows/deploy.yml
Seems that the jbang script in the `quarkusio/action-build-reporter` action is using JDK 21
> Run ~/.jbang/bin/jbang --java 21 --fresh --repos 'quarkus-github-action=https://maven.pkg.github.com/quarkusio/action-build-reporter/' --repos 'mavencentral' io.quarkus.bot:action-build-reporter:999-SNAPSHOT
it also seems that in the previous builds it managed to pull the JDK:
https://github.com/quarkusio/search.quarkus.io/actions/runs/17028620561/job/48267483822
while in the more recent one https://github.com/quarkusio/search.quarkus.io/actions/runs/17201370198/job/48792463604 it failed with
> Error:  [ERROR] No suitable JDK was found for requested version: 21
since we are installing the JDK anyway... let's use the one that that jbang script can reuse instead of downloading another one ?
> Use JDK 21 to build the project
